name: shorebird_update_checker
description: "A Flutter package to check for updates and prompt users to update the app."
version: 0.0.3
homepage: https://github.com/Awaleed/shorebird_update_checker

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  restart_app: ^1.2.1
  shorebird_code_push: ^1.1.3
  store_redirect: ^2.0.1
  upgrader: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
